### ISSUE TITLE
Consonant Assimilation Table is jumpy

### ISSUE THREAD

**Issue by jachinn** [HelenaSabel/linguistic_variation#12]
The table under Consonant Assimilation changes widths and causes the index to the right of the page to change widths as you scroll the page on my MacBook Air (Chrome). It's pretty jarring.

**Comment by HelenaSabel** [comment]
The index to the right changes positions on scrolling (from static, to absolute, to fixed) and that’s what causes the width change. There is still a small "switch" but not as noticeable as before.
