### ISSUE TITLE
Index when viewing corpus sticky

### ISSUE THREAD

**Issue by jachinn** [HelenaSabel/linguistic_variation#13]
The index to the right of the page doesn't scroll with the page until you get to the bottom. Since the index is so long, I expected it to have its own scroll bar and was surprised when it didn't move.

**Comment by HelenaSabel** [comment]
I like the idea of a fixed index, but, if it is too long, you can't scroll it due to the fixed position. I'm going to try creating an inner div, but I'm not confident if that would solve the problem. If you have any suggestions, I'll be happy to try them.

**Comment by jachinn** [comment]
Depending on how much you care about older browser compatibility, you can set the `aside` element to `max-height: 100vh` (viewport height). This would allow you, I think, to get rid of the changing positioning while also letting people access the whole index.

**Comment by HelenaSabel** [comment]
Thank you so much for the suggestion, Janis!
