### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by ebeshero** [HelenaSabel/linguistic_variation#16]
@HelenaSabel A small thing--I'd left your index page open in my browser from yesterday, and when I returned to my home computer I just clicked on the links to your professors. The first link to the page for Pilar Lorenzo Gradin is broken because it leads to `http://www.gl-pt.obdurodon.org/usc-es.academia.edu/PilarLorenzoGrad%C3%ADn`.

**Comment by ebeshero** [comment]
And speaking of links, what about including a link to this GitHub repository on your site? (And a link on the GitHub repository itself _to_ your site?) I'll look forward to reading more of your representation of your editing and collation work, too. Somehow I think you'll want a lot more introductory text on your index and about pages, and it can be hard to figure out the right balance: how basic should the index page be? (Probably a little more informative than telling the reader you are providing a "very specific edition," since the next click from the index page leads immediately to highly specialized information.)

**Comment by HelenaSabel** [comment]
Thank you, Elisa!
About the contents of the site, mostly is place holding text until I find the time to write something. My intention was to link from the index to different parts of "About" page, but since I don't have anything there yet, I linked to the only functioning part of the site.
