### ISSUE TITLE
overlapping abbreviations

### ISSUE THREAD

**Issue by HelenaSabel** [HelenaSabel/linguistic_variation#7]
In your collations, have ever you run into abbreviations that take part of two tokens?

Given the following transcription:

`A: sempre est`
`B: semprest`

Witness A presents a synalepha. Witness B presents a crasis. There is no linguistic variation: it’s merely a graphic one because the number of syllables is the same. Since I divide the tokens, my edition would say:

`A (synalepha): sempre`
`B: sempr’`
`AB: est`

The problem arises when B presents an abbreviation (adding a new graphic variant to annotate and an overlapping issue):

`A: sempre est`
`B: semp<ex>re</ex>st`

The way I see it, I only have two options:
a) Due to the abbreviation, I open an `<app>` tagset considering that both tokens belong to the same segmentation:

`A (synalepha): sempre est`
`B (abbreviation): semp<ex>r’ e</ex>st`

B) I create two `<ex>` elements indicating somehow that they belong to the same abbreviation.

`A (synalepha): sempre`
`B (abbreviation): semp<ex xml:id="re1" next="#re2">r</ex>’`
`A: est`
`B (abbreviation): <ex xml:id="re2" prev="#re1">e</ex>st`

What do you think?

P.S.: There could be a third option:

`A (synalepha): sempre`
`B (abbreviation): semp<ex>re</ex>`
`A: est`
`B (crase): ’st`

It is a estrange convention though...

**Comment by djbpitt** [comment]
`semp<ex>r<supplied reason="synalepha">e</supplied> e</ex>st`
