### ISSUE TITLE
Data visualization enhancement

### ISSUE THREAD

**Issue by HelenaSabel** [HelenaSabel/linguistic_variation#9]
- [x] Correct misspelling of "transcription"
- [x] Headers of witnesses
- [x] Criteria box: non-wrap the space between the input and its legend
- [x] Add elements regarding deletions with XSLT instead of JavaScript
- [x] Check how the additions are being display because there seem to be some issues
- [x] Delete space before periods
- [ ] Check that the space around apostrophes is correct
- [x] Add padding for _refrães_ and _fiindas_
- [x] Combining dot bellow is not being displayed

**Comment by ebeshero** [comment]
@HelenaSabel I'm not sure if this is the appropriate place to leave this suggestion, but you may want to make a correction on your nifty Workflow visualization on this page: http://www.gl-pt.obdurodon.org/about.php . You are spelling the word "Transcription" without the "n" in the three boxes along the top.

**Comment by HelenaSabel** [comment]
Thank you, @ebeshero ! I'll add it to the list.
